# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a10421678230eb90d5e02c876ae6235f5b1d8a337ae60334027c2e8467fbe0faa8942299889a3bd4b056eab1136c888f8da09797bf96cb16c9a75e1f415b5e1a

test:
  secret_key_base: 7de28bddedbe232403f1a9c24cbf52ac5192629afc06139fb11aa2d3ba1a6af1158ad54c1d82f7b46e657405396bf807a90b51195459c15b2148650f35b85475

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
